/* ============================================
   AI Hub v2.0 — Export Utilities
   Copy, PDF, Print support
   ============================================ */

const ExportUtils = (function() {
  'use strict';

  /**
   * Copy text to clipboard with visual feedback
   * @param {string} text - Text to copy
   * @param {HTMLElement} [triggerBtn] - Button that triggered the copy (for visual feedback)
   * @returns {Promise<boolean>}
   */
  async function copyToClipboard(text, triggerBtn) {
    try {
      await navigator.clipboard.writeText(text);

      if (triggerBtn) {
        const originalHTML = triggerBtn.innerHTML;
        const originalClass = triggerBtn.className;
        triggerBtn.classList.add('copied');
        triggerBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg> Copied';
        setTimeout(function() {
          triggerBtn.innerHTML = originalHTML;
          triggerBtn.className = originalClass;
        }, 2000);
      }

      return true;
    } catch (err) {
      console.error('[ExportUtils] Copy failed:', err);
      // Fallback for older browsers
      try {
        const textarea = document.createElement('textarea');
        textarea.value = text;
        textarea.style.cssText = 'position:fixed;opacity:0;';
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        return true;
      } catch (fallbackErr) {
        return false;
      }
    }
  }

  /**
   * Generate a printable HTML page and trigger print
   * @param {string} title - Document title
   * @param {string} htmlContent - HTML content to print
   */
  function printContent(title, htmlContent) {
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) return;

    printWindow.document.write([
      '<!DOCTYPE html><html><head>',
      '<title>' + title + '</title>',
      '<style>',
      'body { font-family: Inter, -apple-system, sans-serif; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; }',
      'h1 { font-size: 24px; border-bottom: 2px solid #00E5FF; padding-bottom: 12px; margin-bottom: 24px; }',
      'h2 { font-size: 18px; margin-top: 24px; color: #333; }',
      'h3 { font-size: 15px; color: #555; }',
      'p { margin: 8px 0; }',
      'ul, ol { margin: 8px 0 8px 24px; }',
      '.badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }',
      '.badge--strong { background: #d1fae5; color: #065f46; }',
      '.badge--risk { background: #fee2e2; color: #991b1b; }',
      '.badge--watch { background: #fef3c7; color: #92400e; }',
      '.section { margin-bottom: 24px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; }',
      '.meta { font-size: 12px; color: #6b7280; margin-top: 24px; }',
      '@media print { body { padding: 20px; } }',
      '</style>',
      '</head><body>',
      '<h1>' + title + '</h1>',
      htmlContent,
      '<div class="meta">Generated by AI Hub v2.0 — The Confidence Engine — ' + new Date().toLocaleDateString() + '</div>',
      '</body></html>'
    ].join('\n'));

    printWindow.document.close();
    setTimeout(function() {
      printWindow.print();
    }, 300);
  }

  /**
   * Download content as a text/markdown file
   * @param {string} filename - File name with extension
   * @param {string} content - File content
   * @param {string} [mimeType] - MIME type (default: text/plain)
   */
  function downloadFile(filename, content, mimeType) {
    mimeType = mimeType || 'text/plain';
    const blob = new Blob([content], { type: mimeType + ';charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Format an object/data into a printable HTML string
   * @param {Object} data - Data object with sections
   * @returns {string} HTML string
   */
  function formatForPrint(data) {
    let html = '';

    if (data.summary) {
      html += '<div class="section"><h2>Summary</h2><p>' + data.summary + '</p></div>';
    }

    if (data.sections && Array.isArray(data.sections)) {
      data.sections.forEach(function(section) {
        html += '<div class="section">';
        html += '<h2>' + (section.title || '') + '</h2>';
        if (section.content) {
          html += '<p>' + section.content + '</p>';
        }
        if (section.items && Array.isArray(section.items)) {
          html += '<ul>';
          section.items.forEach(function(item) {
            html += '<li>' + item + '</li>';
          });
          html += '</ul>';
        }
        html += '</div>';
      });
    }

    return html;
  }

  /**
   * Show a toast notification
   * @param {string} message
   * @param {string} [type] - 'success', 'error', 'info'
   */
  function showToast(message, type) {
    type = type || 'success';
    const toast = document.createElement('div');
    toast.className = 'v2-toast v2-toast--' + type;
    toast.textContent = message;

    // Ensure toast styles exist
    if (!document.getElementById('v2-toast-styles')) {
      const style = document.createElement('style');
      style.id = 'v2-toast-styles';
      style.textContent = [
        '.v2-toast { position: fixed; bottom: 24px; right: 24px; padding: 12px 20px; border-radius: 8px; font-size: 14px; font-weight: 500; z-index: 9999; animation: toastIn 0.3s ease, toastOut 0.3s ease 2.7s forwards; pointer-events: none; }',
        '.v2-toast--success { background: #00D68F; color: #0D0F13; }',
        '.v2-toast--error { background: #FF4C6A; color: white; }',
        '.v2-toast--info { background: #00E5FF; color: #0D0F13; }',
        '@keyframes toastIn { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }',
        '@keyframes toastOut { from { opacity: 1; } to { opacity: 0; } }',
        '@media (max-width: 1024px) { .v2-toast { bottom: 88px; } }'
      ].join('\n');
      document.head.appendChild(style);
    }

    document.body.appendChild(toast);
    setTimeout(function() {
      if (toast.parentNode) toast.parentNode.removeChild(toast);
    }, 3000);
  }

  return {
    copyToClipboard: copyToClipboard,
    printContent: printContent,
    downloadFile: downloadFile,
    formatForPrint: formatForPrint,
    showToast: showToast
  };
})();
